### ISSUE TITLE
Discussion: APIs to keep

### ISSUE THREAD

**Issue by GiggleLiu** [QuantumBFS/YaoAPI.jl#1]
Not sure about:
1. `partial_tr`
2. `state` et al
3. `zero_state` et al
4. `datatype`

shall we remove "array" relate interface: 1, 2, 4?

Or just keep all of them for simplicity?

Shall we also add concrete types in this API package?

**Comment by GiggleLiu** [comment]
A naive approach:
Keep all exported functions and types in `YaoArrayRegisters` and `YaoBlocks`, including concrete types. So that people can port any level of Yao. Any drawback of doing this?

**Comment by GiggleLiu** [comment]
Another option is just abstract types and implementation irrelevant APIs.

So, I am wondering what is your using case in YaoIR requiring?
@Roger-luo

**Comment by Roger-luo** [comment]
I think we can have `partial_tr` this is quite useful, and I think it is compatible with real experiment (which simply means mask off some qubits, and don't look at them)

I only need `instruct!` and `AbstractRegister` related interfaces so far.
